spring:
  datasource:
    url: jdbc:postgresql://ft-transaction-db:5432/ft_transaction_db
    driver-class-name: org.postgresql.Driver
    username: ftdb_user
    password: ftdb_user
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      org:
        hibernate:
          dialect: PostgreSQLDialect

server:
  port: 8080

finance-tracker:
  security:
    client-secret: ea4723c1-5fd4-4f64-adf6-5bb283f3a52b
    client-id: transaction-service