# The ConfigServer's local development configurations
spring:
  cloud:
    config:
      server:
        native:
          addLabelLocations: false
          search-locations:
            - classpath:config/{application}/{profile}
            - classpath:config

server:
  port: 8888